source 'https://rubygems.org'

gem 'github-pages'
gem 'jekyll-github-metadata'
gem 'jekyll-remote-theme'
gem 'jekyll-redirect-from'
gem "webrick"

group :development, :test do
  gem 'rake'
  gem 'html-proofer'
end
