require 'html-proofer'
require 'yaml'

CONFIG  = YAML.load_file '_config.yml'
BASEURL = ENV['BASEURL'] || CONFIG.dig('baseurl')

task :build do
  sh "bundle exec jekyll clean"
  sh "bundle exec jekyll build -b '#{BASEURL}' -d '_site#{BASEURL}'"
end

task :test do
  opts = {
    check_external_hash: true,
    allow_hash_href: true,
    check_html: true,
    disable_external: true,
    empty_alt_ignore: true,
    assume_extension: true,
    only_4xx: true
  }
  HTMLProofer.check_directory('./_site', opts).run
end
