name: ci:test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current state"
        uses: actions/checkout@v6
      - name: "Save Python and Node versions to env"
        run: |
          echo "PYTHON_VERSION=$(cat '.python-version')" >> ${GITHUB_ENV}
          echo "NODE_VERSION=$(cat '.nvmrc')" >> ${GITHUB_ENV}
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Set up Node"
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.15"
      - name: "Install invenio-cli"
        run: |
          uv tool install invenio-cli
      - name: "Check Invenio's requirements"
        run: |
          invenio-cli check-requirements
      - name: "Setup mandatory files"
        run: |
          echo -e "[cli]\nproject_dir = "$PWD"\nservices_setup = False" >> .invenio.private
          echo -e FLASK_SECRET_KEY="some random value" >> .env
      - name: "Install project dependencies"
        run: |
          invenio-cli install
          invenio-cli translations compile
      - name: "Run black & tests"
        run: |
          E2E=yes pipenv run ./run-tests.sh
      - name: "Upload screenshots"
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: screenshots
          path: screenshots/*.png
